spring.config.import=optional:file:env.properties
spring.application.name=the_last_dance
# SERVER CONFIG
server.port=${PORT:3001}
# DB CONFIG
spring.datasource.url=jdbc:postgresql://localhost:5432/the_last_dance
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver=org.postgresql.Driver
# HIBERNATE
spring.jpa.hibernate.ddl-auto=update
#supersecret=${SUPERSECRET}
# CLOUDINARY
#cloudinary.name=${CLOUDINARY_NAME}
#cloudinary.apikey=${CLOUDINARY_API_KEY}
#cloudinary.secret=${CLOUDINARY_API_SECRET}